### ISSUE TITLE
GUI Settings not working

### ISSUE THREAD

**Issue by SamedVossberg** [neuromodulation/py_neuromodulation#377]
I don't know if this might already be fixed on another branch but at least on the gui branch the Settings don't really work. 
They do not change or affect the stream in the backend. Although setting updated are logged in the backend, the actual settings of the stream do not change nor does the data being pushed through the socket. 

This does not as initially thought only affect PSD but all settings and features.

**Comment by timonmerk** [comment]
I can reproduce the bug. Also on the `better_settings_layout` branch I am not able to see under localhost:54321 the webpage.

When looking at localhost:50001 I can see the frontpage, but when clicking on settings I get the following exceptions:

```
[FastAPI INFO (11:09:28)]: connection open
[FastAPI INFO (11:09:28)]: connection closed
[FastAPI ERROR (11:09:28)]: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/staticfiles.py", line 91, in __call__
    assert scope["type"] == "http"
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
[FastAPI INFO (11:09:28)]: connection open
[FastAPI INFO (11:09:28)]: connection closed
[FastAPI access (11:09:29)]: 127.0.0.1:63864 - "GET /api/settings HTTP/1.1" 200
[FastAPI INFO (11:09:29)]: ('127.0.0.1', 63866) - "WebSocket /ws" [accepted]
[FastAPI ERROR (11:09:29)]: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/routing.py", line 93, in app
    await func(session)
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/gui/backend/app_backend.py", line 423, in websocket_endpoint
    await self.websocket_manager_features.connect(websocket)
  File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/gui/backend/app_socket.py", line 20, in connect
    await websocket.accept()
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/websockets.py", line 109, in accept
    await self.send({"type": "websocket.accept", "subprotocol": subprotocol, "headers": headers})
  File "/Users/Timon/Documents/py_neuromodulation/.venv/lib/python3.11/site-packages/starlette/websockets.py", line 79, in send
    raise RuntimeError(
RuntimeError: Expected ASGI message "websocket.send" or "websocket.close", but got 'websocket.accept'

```

**Comment by timonmerk** [comment]
Ok, after looking more into depth into that I found the bug. When starting the stream we're not taking into account the updated settings. The run function is simply started here: https://github.com/neuromodulation/py_neuromodulation/blob/976cef23c8cd3e222a863277901be961e46f9385/py_neuromodulation/gui/backend/app_pynm.py#L40 

But we would need to update the settings like that:

`self.stream.settings = self.settings`

I will push this change into your branch @SamedVossberg.

@toni-neurosc When doing those updates I get a pydantic error:

> [FastAPI INFO (11:42:14)]: Starting stream
> [FastAPI access (11:42:14)]: ::1:50499 - "POST /api/stream-control HTTP/1.1" 200
> [FastAPI INFO (11:42:14)]: setup stream Process
> Task exception was never retrieved
> future: <Task finished name='Task-31' coro=<Stream.run() done, defined at /Users/Timon/Documents/py_neuromodulation/py_neuromodulation/stream/stream.py:200> exception=TypeError("Resampler.__init__() got an unexpected keyword argument '__field_type__'")>
> Traceback (most recent call last):
>   File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/stream/stream.py", line 248, in run
>     self.data_processor = DataProcessor(
>                           ^^^^^^^^^^^^^^
>   File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/stream/data_processor.py", line 64, in __init__
>     self.preprocessors = DataPreprocessor(
>                          ^^^^^^^^^^^^^^^^^
>   File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/processing/data_preprocessor.py", line 69, in __init__
>     self.preprocessors: list[NMPreprocessor] = [
>                                                ^
>   File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/processing/data_preprocessor.py", line 70, in <listcomp>
>     instantiate_preprocessor(preprocessor_class, preprocessor_name)
>   File "/Users/Timon/Documents/py_neuromodulation/py_neuromodulation/processing/data_preprocessor.py", line 67, in instantiate_preprocessor
>     return preprocessor_class(**args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: Resampler.__init__() got an unexpected keyword argument '__field_type__'

I even get this error if all preprocessing steps are deleted, so the list of empty: `preprocessing: []`.

It would be great to find out why that could be the reason.
